name: Infuse
version: '$version'
main: com.catadmirer.infuseSMP.Infuse
api-version: '1.21.4'
authors: [CatAdmirer, TurboJax]
softdepend: [PlaceholderAPI]
commands:
  infuse:
    description: Base command for Infuse
    usage: /infuse <gui|reload>
  controls:
    description: Toggle controls between offhand and mainhand.
    usage: /controls
  cleareffects:
    description: Clear all effects from a player.
    usage: /cleareffects <player>
    permission: op
  lspark:
    description: Activates the first ability.
    usage: /lspark
  rspark:
    description: Activates the second ability.
    usage: /rspark
  ldrain:
    description: Drains the first ability.
    usage: /ldrain
  rdrain:
    description: Drains the second ability.
    usage: /rdrain
  swap:
    description: Swaps the effects between slots 1 and 2.
    usage: /swap
  trust:
    description: Trust a player
    usage: /trust <player>
  untrust:
    description: Untrust a player
    usage: /untrust <player>
  recipes:
    description: Check the limits
    usage: /recipes
  draw:
    description: Draws a line between two coordinates
    usage: /draw <x1> <y1> <z1> <x2> <y2> <z2>
permissions:
  ability.use:
    description: Allows the player to use abilities.
    default: false
